name: Java Maven Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Maven
        run: mvn -version

      - name: Build Project
        run: mvn -f .github/java-github-actions-demo/pom.xml clean package