name: Setup Java Demo

on:
  push:

jobs:
  java-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Check Java Version
        run: java -version

      - name: Check Java Compiler Version
        run: javac -version